id: I76D1EFFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T16:48:32+00:00'
last_modified: '2022-06-07T22:36:14.393183+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20852
  title: སྔོན་མོ་སྤང་ལས་འཁྲུངས་པའི་སེམས་ཀྱི་རོལ་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '6131':
      image_group_id: I5780
      title: ''
      total_pages: 328
      order: 1
      base_file: 6131.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
