id: P004400
initial_creation_type: ocr
source_metadata:
  id: bdr:W20852
  title: སྔོན་མོ་སྤང་ལས་འཁྲུངས་པའི་སེམས་ཀྱི་རོལ་མོ
  author: ''
  volumes:
    900d0424481e43839100119ef3645b8b:
      image_group_id: I5780
      title: ''
      volume_number: 1
      total_pages: 328
