id: P004400
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20852
  title: སྔོན་མོ་སྤང་ལས་འཁྲུངས་པའི་སེམས་ཀྱི་རོལ་མོ
  author: ''
  volumes:
    900d0424481e43839100119ef3645b8b:
      image_group_id: I5780
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
